crypto-api:
  extension:
    aes:
      encrypt:
        enable: true
        apis:
          user:
            aes-key: f5d830d77163a58f
            paths:
              - /demo/encrypt/**
      decrypt:
        enable: true
        apis:
          user:
            aes-key: f5d830d77163a58f
            paths:
              - /demo/decrypt/**