crypto-api:
  encrypt:
    enable: true
    apis:
      demo1:
        paths:
          - /demo/*/test
        aes-key: f5d830d77163a58f
  decrypt:
    enable: true
    apis:
      demo1:
        paths:
          - /demo/test
        aes-key: f5d830d77163a58f